on: push
name: Demo Github Actions Build & Deploy
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        uses: actions/setup-node@v1
        with:
          args: install
      - name: npm test
        uses: actions/setup-node@v1
        with:
          args: run test
      - name: build & publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: muhfaridzia/demo-github-action-react-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
