on: push
name: Demo Github actions & Deploy
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        uses: actions/npm@v1
        with:
          args: install
      - name: npm test
        uses: actions/npm@v1
        with:
          args: run test
      - name: docker build
        uses: actions/docker/cli@v1
        with:
          args: build -t muhfaridzia/demo-github-action-react-app .
      - name: docker login
        uses: actions/docker/login@v1
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@v1
        with:
          args: push muhfaridzia/demo-github-action-react-app